export const sitemapData = `<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://koolairpump.com/</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/sign-in</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/search</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/datasheets</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/about-us</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/koolair-lifestyle</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/collections/pm-500-series</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/collections/pm-1000-series</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/collections/spm-1000-series</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/collections/pm-300-series</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/collections/tpm-1000-series</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/collections/koolair-replacement-parts</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/faq</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/warranty</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/terms-and-conditions</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/what-is-a-koolair-pump</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/contact-us</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/sign-up</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/forgot-password</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/koolair-tpm1000</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/koolair-pm500-115v</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/koolair-pm500-230v</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/koolair-pm1000-115v</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/koolair-pm1000-230v</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/pm1000-we</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/pm500-we</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/koolair-spm1000-115v</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/koolair-spm1000-230v</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-21</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-22</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-23</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-24</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-25</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-26</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-27</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-28</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-29</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-30</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-33</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka500-31</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-21</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-22</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-23</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-24</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/pm300-12</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-25</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-26</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-27</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/ka1000-28</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/kat1000-21</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/kat1000-22</loc>
  </url>
  <url>
    <loc>https://koolairpump.com/products/kat1000-23</loc>
  </url>
</urlset>`;
